# Generated by Django 3.2.2 on 2021-05-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('page_id', models.IntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=200, null=True)),
                ('sub_text', models.CharField(max_length=200, null=True)),
                ('ad_id', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.page')),
            ],
        ),
    ]
