# Generated by Django 3.2.2 on 2021-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_advertisement_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='started_running_on',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
