# Generated by Django 3.2.2 on 2021-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210524_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
