# Generated by Django 3.2.2 on 2021-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_advertisement_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
