# Generated by Django 3.2.2 on 2021-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_advertisement_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='memo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
