# Generated by Django 3.2.2 on 2021-06-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_alter_page_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_notable',
            field=models.BooleanField(default=False),
        ),
    ]
