# Generated by Django 3.2.2 on 2021-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0009_page_is_notable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
