# Generated by Django 3.2.2 on 2021-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_alter_page_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='lp_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
